package com.spotday.app.model

import kotlin.math.ln
import kotlinx.serialization.Serializable

enum class PlaceType {
    MUSEUM,
    PARK,
    RESTAURANT,
    WATERFRONT,
    HISTORIC_SITE,
    SHOPPING,
    NIGHTLIFE,
    // New activity categories
    ENTERTAINMENT,  // Comedy clubs, theaters, live shows
    GAMES,          // Escape rooms, bowling, arcades
    OUTDOOR,        // Kayaking, hiking, bike rentals
    WELLNESS,       // Spas, yoga, bathhouses
    BREWERY,        // Breweries, wineries, distilleries
    CLASS,          // Cooking, pottery, art workshops
    MARKET,         // Farmers markets, flea markets
    SPORTS,         // Golf, climbing gyms, batting cages
    ZOO,            // Zoos, aquariums
    CINEMA,         // Movie theaters
    ATTRACTION      // Tourist attractions, landmarks
}

enum class EventType {
    CONCERT,
    SPORTS,
    THEATER,
    COMEDY,
    FOOD_FESTIVAL,
    STREET_FAIR,
    CLASS_WORKSHOP
}

enum class EventSource {
    TICKETMASTER,  // Concerts, sports, theater, comedy
    EVENTBRITE     // Food festivals, street fairs, workshops, classes
}

enum class ServiceStyle {
    QUICK,      // 30 min - food trucks, cafes, fast casual, grab-and-go
    CASUAL,     // 60 min - neighborhood restaurants, diners, bistros
    FORMAL      // 90 min - fine dining, upscale (dinner only)
}

enum class StopType {
    MAIN,           // Primary itinerary stop (numbered pin)
    WAYPOINT,       // Scenic pass-through point (small dot)
    QUICK_STOP,     // Coffee/photo break (small icon)
    FREE_TIME       // Exploration period (no pin, just suggestion)
}

enum class QuickStopType {
    COFFEE,
    PHOTO_SPOT,
    VIEWPOINT,
    STREET_ART
}

/**
 * Opening hours for a specific day.
 * Times are in "HH:mm" format (24-hour).
 * For overnight closing (e.g., bars), close might be "02:00" with open "16:00".
 */
data class DayHours(
    val open: String,   // "11:00"
    val close: String   // "22:00" or "02:00" for overnight
)

/**
 * Weekly opening hours for a place.
 * null value for a day means the place is closed that day.
 */
data class WeeklyHours(
    val monday: DayHours? = null,
    val tuesday: DayHours? = null,
    val wednesday: DayHours? = null,
    val thursday: DayHours? = null,
    val friday: DayHours? = null,
    val saturday: DayHours? = null,
    val sunday: DayHours? = null
) {
    /**
     * Get hours for a specific day of week (1=Sunday, 7=Saturday, matching Calendar.DAY_OF_WEEK)
     */
    fun getHoursForDay(dayOfWeek: Int): DayHours? {
        return when (dayOfWeek) {
            java.util.Calendar.SUNDAY -> sunday
            java.util.Calendar.MONDAY -> monday
            java.util.Calendar.TUESDAY -> tuesday
            java.util.Calendar.WEDNESDAY -> wednesday
            java.util.Calendar.THURSDAY -> thursday
            java.util.Calendar.FRIDAY -> friday
            java.util.Calendar.SATURDAY -> saturday
            else -> null
        }
    }
}

enum class ExplorationMode {
    ONE_AREA,    // Stay in one neighborhood (walkable)
    CITY_WIDE    // Visit highlights across town
}

@Serializable
enum class NeighborhoodTier(val value: Int) {
    ESSENTIAL(1),   // Must-see, highest density of things to do
    CLASSIC(2),     // Worth visiting, iconic but less dense
    LOCAL(3)        // Local favorites, skip unless exploring
}

@Serializable
enum class DataSource {
    CURATED,        // Human-verified, high quality
    LLM,            // Generated by LLM, needs verification
    ALGORITHM       // Derived from venue clustering
}

data class CityProfile(
    val id: String,
    val name: String,
    val country: String,
    val size: String,           // "large", "medium", "small"
    val density: String,        // "very_dense", "moderate", "spread_out"
    val centerLat: Double,
    val centerLng: Double,
    val estimatedHappeningAreas: Int
)

@Serializable
data class Neighborhood(
    val id: String,
    val name: String,
    val cityId: String,                     // "san_francisco", "austin", "tokyo"
    val tier: NeighborhoodTier = NeighborhoodTier.CLASSIC,
    val centerLat: Double,
    val centerLng: Double,
    val radiusMeters: Int = 800,
    val vibes: List<String> = emptyList(),  // ["foodie", "nightlife", "artsy"]
    val dataSource: DataSource = DataSource.CURATED,
    val adjacentNeighborhoods: List<String> = emptyList(),
    val description: String? = null         // "Highest concentration of trendy restaurants"
)

data class Waypoint(
    val name: String,
    val lat: Double,
    val lng: Double,
    val description: String? = null  // "Pass by Saints Peter & Paul Church"
)

data class ScenicRoute(
    val id: String,
    val fromArea: String,           // e.g., "north_beach"
    val toArea: String,             // e.g., "chinatown"
    val waypoints: List<Waypoint>,
    val description: String,        // "Walk through Washington Square..."
    val addedMinutes: Int           // Extra time vs direct route
)

data class Event(
    val id: String,
    val name: String,
    val description: String,
    val eventType: EventType,
    val venueName: String,
    val venueLatitude: Double,
    val venueLongitude: Double,
    val startHour: Int,      // 0-23
    val startMinute: Int,    // 0-59
    val durationMinutes: Int,
    val priceMin: Double?,
    val priceMax: Double?,
    val isSoldOut: Boolean = false,
    val ticketUrl: String? = null,
    val popularity: Int = 3,  // 1-5 scale, 5 = most popular (maps to Ticketmaster sort)
    val source: EventSource = EventSource.TICKETMASTER
)

/** Default business hours: 9 AM - 10 PM daily */
val DEFAULT_BUSINESS_HOURS = WeeklyHours(
    monday = DayHours("09:00", "22:00"),
    tuesday = DayHours("09:00", "22:00"),
    wednesday = DayHours("09:00", "22:00"),
    thursday = DayHours("09:00", "22:00"),
    friday = DayHours("09:00", "22:00"),
    saturday = DayHours("09:00", "22:00"),
    sunday = DayHours("09:00", "22:00")
)

data class Place(
    val id: String,
    val name: String,
    val type: PlaceType,
    val lat: Double,
    val lng: Double,
    val rating: Float,
    val isOpen: Boolean = true,
    val priceLevel: Int = 2,      // 1=$, 2=$$, 3=$$$, 4=$$$$
    val estimatedCost: Int = 0,    // Calculated cost per person
    val isOutdoor: Boolean = false, // For weather-aware recommendations
    val serviceStyle: ServiceStyle = ServiceStyle.CASUAL, // Restaurant service style
    val neighborhood: String? = null, // Neighborhood ID for clustering
    val reviewCount: Int = 0,      // 0 = unknown, populated by Google Places API
    val nightlifeCategory: String? = null, // cocktail_bar, dive_bar, rooftop_bar, etc.
    val weeklyHours: WeeklyHours = DEFAULT_BUSINESS_HOURS  // Day-specific opening hours
)

/**
 * Quality score combining rating (60%) and popularity (40%).
 * Falls back to rating-only if reviewCount is unknown (0).
 * Returns 0.0 - 1.0 range.
 */
fun Place.qualityScore(): Float {
    val normalizedRating = rating / 5f
    
    // If no review data yet, rely on rating only (POC / pre-API)
    if (reviewCount == 0) return normalizedRating
    
    val normalizedPopularity = (ln(reviewCount.toFloat() + 1) / ln(5000f)).coerceIn(0f, 1f)
    return normalizedRating * 0.6f + normalizedPopularity * 0.4f
}

data class TransitEstimate(
    val walkingMinutes: Int,
    val transitMinutes: Int,
    val drivingMinutes: Int,
    val distanceKm: Double
)

data class ItineraryStop(
    val place: Place? = null,       // Nullable for free time / waypoint-only stops
    val startTime: String,
    val endTime: String,
    val durationMinutes: Int,
    val distanceFromPreviousKm: Double = 0.0,
    val transitEstimate: TransitEstimate? = null,
    val event: Event? = null,       // Non-null if this stop is for a scheduled event
    val stopType: StopType = StopType.MAIN,
    val waypoint: Waypoint? = null, // For waypoint/quick stop types
    val quickStopType: QuickStopType? = null, // Type of quick stop (coffee, photo, etc.)
    val scenicRoute: ScenicRoute? = null, // Scenic route to this stop (if any)
    val neighborhoodName: String? = null  // For free time suggestions
)

data class UserPreferences(
    val startHour: Int,
    val endHour: Int,
    val totalBudget: Int,
    val activityTypes: List<String>,
    val foodTypes: List<String>,
    val isHungryNow: Boolean = false,
    val isSpontaneousMode: Boolean = false,
    val startLatitude: Double? = null,  // null = use random SF location
    val startLongitude: Double? = null,
    val nightlifeTypes: List<String> = emptyList(),
    val selectedEventIds: List<String> = emptyList(),
    val serviceStyles: List<ServiceStyle> = emptyList(), // Empty = all styles allowed
    val explorationMode: ExplorationMode = ExplorationMode.ONE_AREA // Default to walkable
)

